eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

microservice:
  paymentms:
    endpoints:
      endpoint:
        uri: http://paymentms/payment/doPayment

  orderms:
    endpoints:
      endpoint:
        uri: http://orderms/order/bookOrder/
